### ISSUE TITLE
DatePicker DateUtils from react-day-picker should be removed

### ISSUE THREAD

**Issue by saucevector** [VectorLearning/uui_kit#13]
We should use moment or something for these Utils. the package React Day Picker is a hefty package for making an actual date picker. Unless, it is being somewhere I cannot see.

Right now I can see it is being used for "DateUtils.isDayBefore".

Instead use moment(date1).isBefore(date2, 'day');

**Comment by lefleraa** [comment]
I see no problem with using moment for the isDayBefore stuff. makes sense. We use moment like that elsewhere. No need to introduce an unnecessary util lib. When you say "package React Day Picker is a hefty package" are you suggesting we remove that whole package, or just the DateUtils lib you can choose to include? "React Day Picker" manages ALL the calendar view and calendar interaction elements.

**Comment by saucevector** [comment]
Ya, I saw that after the fact, we are using React Day Picker for the actual calendar module. It looked like you may have written that all yourself, but I see that now. I was referring its use in DatePicker, which only seems to get used for the DateUtils, which we can just use moment for that, probably. Given this is already a required package for the actual calendar component, we wont see much savings in the file size department. I may just close this issue without fixing it.

As a heads up, I am planning on doing a refactor of DatePicker.

**Comment by saucevector** [comment]
Handled with this commit 5c638894b4966a4ba99b523444eeb034f7b88f2c
