### ISSUE TITLE
Needs Explanation: DatePicker is passing a callback for handleDateUpdate

### ISSUE THREAD

**Issue by saucevector** [VectorLearning/uui_kit#14]
The method handleDateUpdate is passing a data object, callback to the prop function "onRangeUpdate". 

This is counter intuitive and would require a reason, since this callback accepts no arguments from the component that fires this callback. We should instead, just fire the this.setState. Unless I am missing the reason why we need to do this as a callback.

**Comment by lefleraa** [comment]
If I understand this correctly, you're curious why we pass data up via the callback instead of letting the picker be an independently managed system? My initial response would be that this is an atom component and doesn't own the main state. It only acts as a control. Whatever parent is using it is ultimately the master of state.

**Comment by lefleraa** [comment]
Have you run into an issue where this doesn't make sense or is cumbersome?

**Comment by saucevector** [comment]
Ya, the initial implementation. If you want to invert control like this, you can bind the data to the props being passed, instead of manipulating state in the parent component. 

So in the example, you essentially require the onRangeUpdate function to accept two arguments, an object and a callback. That callback doesn't receive arguments, so I am not sure the benefit of requiring it to be called on the parent component. Also it has its own state, it is not a stateless component, and the function passed is a setState function with a reference of "self", which is the this of the class component of DatePicker.

**Comment by saucevector** [comment]
This has been fixed in this [commit](https://github.com/VectorLearning/uui_kit/commit/c70a666cc9a15e77fcb67b4bb9198b5b3511bca3) (c70a666cc9a15e77fcb67b4bb9198b5b3511bca3).
